name: Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # Defines the events that trigger the workflow.
    # This workflow will run on pushes to the main branch
    # and pull requests targeting the main branch.
jobs:
  build:
    runs-on: ubuntu-latest
    # Specifies the type of machine to run the job on.
    # Here, it's running on the latest version of Ubuntu.
    environment: test
    # set the enviroment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Checks out your repository code.

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
        # Sets up Node.js environment with the latest LTS version.

      - name: Install dependencies
        run: npm install
        # Installs your project dependencies using npm.

      - name: Create .env file
        run: |
          cat << EOF >> ./.env
          TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}
          EOF
          # This command uses the cat utility along with a here document 
          # (<< EOF) to append text to a file named .env. 
          # The << EOF syntax indicates the start of the here document,
          # and EOF indicates the end. Anything between << EOF and 
          # EOF will be appended to the .env file.

      - name: Run tests
        run: npm test
        # Executes your test script.
